app = "dundermifflininfinity"
primary_region = "ams"

[build]
  image = "tolgayonter/dunderimage:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="doyniupcv"
  CloudinarySettings__ApiKey="869524495815861"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
